module.exports = {
	COMMUNITY_CHAT: 'COMMUNITY_CHAT',
	VERIFY_USER: 'VERIFY_USER',
	USER_CONNECTED: 'USER_CONNECTED',
	USER_DISCONNECTED: 'USER_DISCONNECTED',
	MESSAGE_SENT: 'MESSAGE_SENT',
	MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
	TYPING: 'TYPING',
	LOGOUT: 'LOGOUT',
	PRIVATE_MESSAGE: 'PRIVATE_MESSAGE',
	FILE_SENT: 'FILE_SENT',
	FILE_RECEIVED: 'FILE_RECEIVED'
};